name: Auto Build File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: Checkout codes
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    # 生成数据文件
    - name: Build wrok day json data file
      run: php run.php

    # 提交修改
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply json data file changes