name: Auto Build File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Build wrok day json data file
      run: php run.php

    - name: Commit files
      run: |
        git add README.md
        git commit -m "database change"

    - name: Push changes
      run: git push